version: 1
formatters:
  simple:
    format: '$message' #TODO: levelname?
    style: '$'
  basic:
    format: '$asctime - $message - $levelname: $name'
    #format: '$asctime - $name - $levelname: $message'
    style: '$'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: basic
    filename: 'whatshit.log'
#loggers:
    #  lxml:
    #level: WARNING
root:
  level: DEBUG
  handlers: [console, file]
